apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pillmind-backend-dev
  namespace: argocd
spec:
  project: pillmind
  source:
    repoURL: https://github.com/mayconaraujosantos/pillmind-backend.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: pillmind-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
