apiVersion: v1
kind: ConfigMap
metadata:
  name: pillmind-config
  namespace: pillmind-dev
data:
  PORT: "8080"
  DATABASE_URL: "jdbc:postgresql://postgres:5432/pillmind"
  JWT_EXPIRATION_IN_MS: "86400000"
  BCRYPT_SALT_ROUNDS: "12"
