apiVersion: v1
kind: Secret
metadata:
  name: pillmind-secrets
  namespace: pillmind-dev
type: Opaque
stringData:
  DATABASE_USER: "pillmind_user"
  DATABASE_PASSWORD: "pillmind_pass"
  JWT_SECRET: "pillmind-secret-key-change-in-production-min-256-bits-very-secure"
