apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pillmind-dev

resources:
  - ../../base

replicas:
  - name: pillmind-backend
    count: 2

images:
  - name: pillmind-backend
    newName: pillmind-backend
    newTag: latest
